config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # get 'books/index'
  # get 'books/new'
  # get 'books/edit'
  # get 'books/delete'
  # get 'books/update'
  # get 'book/index'
  # get 'book/new'
  # get 'book/edit'
  # get 'book/show'
  # delete 'book/delete'
  # post 'book/create'
  # put 'book/update'

  match '/book/list', to: 'book#index', via: [:get]
  match '/book/book_list', to: 'book#book_list', via: [:post,:get]
  resources :students
  resources :books
  root to: "books#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  has_one :cover
  belongs_to :subject

end

app/models/cover.rb
class Cover < ApplicationRecord

  belongs_to :book

end

app/models/student.rb
class Student < ApplicationRecord

  before_save :i_am_before_save

  after_save :i_am_after_save

  validates :first_name,:last_name,:email,:graduation, presence: true

  VALID_EMAIL_REGEX= /^(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})$/i

  validates :email ,uniqueness:{case_sensetive:false},
            format:{with:VALID_EMAIL_REGEX,multiline:true}


  validates :first_name,:last_name ,length: { minimum: 4, maximum: 100 }
    # validates :email,
    #           format: { with: /^(.+)@(.+)$/, message: "Email invalid"  },
    #           uniqueness: { case_sensitive: false },
    #           length: { minimum: 4, maximum: 254 }



  def i_am_before_save

    p "=====I am before save ================="
    p self
  end

  def i_am_after_save

    p "=====I am after save ================="

    self.last_name = "#{self.last_name}- shivait"
    p self.save
    p self

  end



  def self.test_class_method



  end

  def test_instance_method



  end





end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :books
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base



end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  def index
    @books = Book.all
  end

  def new

    @book = Book.new
  end

  def create

    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: "Book was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end

  end

  def show


    @book = Book.find(params[:id])

  end

  def edit
    @book = Book.find(params[:id])
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }

    end
  end

  def update
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: "Book was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }

      end
    end


  end


private

  def book_params
    params.require(:book).permit(:name, :description, :author, :price,:subject_id)
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy ]

  before_action :i_am_before_index
  after_action :i_am_after_index,only: [ :show, :edit, :update, :destroy ]
  # GET /students or /students.json
  def index
    p "i am inside index"
    @students = Student.all
  end

  def i_am_before_index
    p "=======i_am_before_index"

  end

  def i_am_after_index
    p "=======i_am_after_index"

  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  def list

  end
  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:first_name, :last_name, :email, :graduation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>


  <div class="field">
    <%= form.label :subject %>
    <%#= form.select :subject_id, @subjects, {}, {class: 'form-control', required: true, selected: @subject} %>

    <%= form.collection_select :subject_id, Subject.all, :id, :name %>
  </div>





  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/delete.html.erb
<h1>Book#delete</h1>
<p>Find me in app/views/book/delete.html.erb</p>

app/views/books/edit.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', "/books" %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<table>
  <thead>
  <tr>
    <th class="header">Name</th>
    <th class="header">Description</th>
    <th class="header">Author</th>
    <th class="header">Price</th>
    <th class="header">Subject</th>

  </tr>
  </thead>

  <tbody>
  <% @books.each do |book| %>
    <tr>
      <td><%= book.name %></td>
      <td><%= book.description %></td>
      <td><%= book.author %></td>
      <td><%= book.price %></td>
      <td><%= book.subject.name rescue "" %></td>
      <td><%= link_to 'Show', book %></td>
      <td><%= link_to 'Edit', edit_book_path(book) %></td>
      <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', "/books/new",:style=>"color:red"%>


<style>

  .header{
    background: #666666;
  }

</style>

app/views/books/new.html.erb
<h1>Edit Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', "/books" %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @book.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @book.description %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Price:</strong>
  <%= @book.price %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @book.subject.name %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoValidations</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <% if user_signed_in? %>

    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>

  <% else %>

    <%= link_to "Sign in ", new_user_session_path, :method => :get %>

  <% end %>
    <%= yield %>


  </body>
</html>

app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :graduation %>
    <%= form.text_field :graduation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Graduation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.first_name %></td>
        <td><%= student.last_name %></td>
        <td><%= student.email %></td>
        <td><%= student.graduation %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', "/students/new"%>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @student.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @student.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @student.email %>
</p>

<p>
  <strong>Graduation:</strong>
  <%= @student.graduation %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>